apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app: auth-service
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "change-me"
  KEYCLOAK_CLIENT_SECRET_PUBLIC: "change-me"
  KEYCLOAK_CLIENT_SECRET_CORP: "change-me"
